version: '2'
services:
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - '80:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:pass@server:5432/dbname
      HASURA_GRAPHQL_ACCESS_KEY: hasurakey
    command:
      - graphql-engine
      - serve
      - --enable-console
